name: langfy
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  get: ^4.7.2
  flutter_svg: ^2.0.17
  shared_preferences: ^2.2.2
  intl_phone_field: ^3.2.0
  dropdown_button2: ^2.3.9
  bottom_picker: ^3.0.0
  date_picker_timeline: ^1.2.6
  

dev_dependencies:
  flutter_launcher_icons: "^0.14.3"
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/icons/navbar/
    - assets/icons/payment/
    - assets/images/
    - assets/translations/

  fonts:
    - family: SpotifyMix
      fonts:
      - asset: assets/fonts/spotify-mix/SpotifyMix-Bold.ttf
      - asset: assets/fonts/spotify-mix/SpotifyMix-BoldItalic.ttf
        style: italic
      - asset: assets/fonts/spotify-mix/SpotifyMix-Extrabold.ttf
      - asset: assets/fonts/spotify-mix/SpotifyMix-ExtraboldItalic.ttf
        style: italic
      - asset: assets/fonts/spotify-mix/SpotifyMix-Light.ttf
      - asset: assets/fonts/spotify-mix/SpotifyMix-LightItalic.ttf
        style: italic
      - asset: assets/fonts/spotify-mix/SpotifyMix-Medium.ttf
      - asset: assets/fonts/spotify-mix/SpotifyMix-MediumItalic.ttf
        style: italic
      - asset: assets/fonts/spotify-mix/SpotifyMix-Regular.ttf
      - asset: assets/fonts/spotify-mix/SpotifyMix-RegularItalic.ttf
        style: italic